#!/usr/bin/python3
if __name__ == "__main__":
    import sys
    fp = open(sys.argv[1], "r")
    argc = len(sys.argv)

    if (argc == 2):
        for line in fp:
            num = int(line)
            i = 2
            while num % i != 0:
                i = i + 1
            print("{:d}={:d}*{:d}".format(num, int(num / i), i))
